import type { Business } from "./types";

export const businesses: Business[] = [
  {
    id: "1",
    name: "Harbor Roast Coffee",
    category: "Food & Beverage",
    address: "412 Waterfront Ave",
    city: "Charleston",
    state: "SC",
    lat: 32.7765,
    lng: -79.9311,
    vestimate: 485000,
    annualRevenue: 620000,
    employees: 12,
    founded: 2016,
    sqft: 1800,
    description:
      "Specialty coffee roastery and café with strong local following and wholesale accounts.",
  },
  {
    id: "2",
    name: "Summit Auto Care",
    category: "Automotive",
    address: "88 Industrial Blvd",
    city: "Greenville",
    state: "SC",
    lat: 34.8526,
    lng: -82.394,
    vestimate: 920000,
    annualRevenue: 1450000,
    employees: 18,
    founded: 2009,
    sqft: 5200,
    description:
      "Full-service auto repair and tire shop with loyal fleet contracts and high repeat traffic.",
  },
  {
    id: "3",
    name: "Pine & Oak Home Goods",
    category: "Retail",
    address: "15 King Street",
    city: "Charleston",
    state: "SC",
    lat: 32.7812,
    lng: -79.9316,
    vestimate: 710000,
    annualRevenue: 980000,
    employees: 9,
    founded: 2014,
    sqft: 2400,
    description:
      "Curated home décor boutique in a high-foot-traffic historic district location.",
  },
  {
    id: "4",
    name: "Blue Ridge Fitness Studio",
    category: "Health & Wellness",
    address: "220 College Ave",
    city: "Asheville",
    state: "NC",
    lat: 35.5951,
    lng: -82.5515,
    vestimate: 395000,
    annualRevenue: 510000,
    employees: 7,
    founded: 2019,
    sqft: 3200,
    description:
      "Boutique fitness studio with membership-based revenue and strong class retention.",
  },
  {
    id: "5",
    name: "Lowcountry Dental Group",
    category: "Healthcare",
    address: "601 Medical Park Dr",
    city: "Mount Pleasant",
    state: "SC",
    lat: 32.8323,
    lng: -79.8284,
    vestimate: 1850000,
    annualRevenue: 2400000,
    employees: 22,
    founded: 2005,
    sqft: 4100,
    description:
      "Established dental practice with insured patient base and modern equipment.",
  },
  {
    id: "6",
    name: "Coastal Pet Supply",
    category: "Retail",
    address: "903 Highway 17",
    city: "Myrtle Beach",
    state: "SC",
    lat: 33.6891,
    lng: -78.8867,
    vestimate: 560000,
    annualRevenue: 740000,
    employees: 11,
    founded: 2012,
    sqft: 3600,
    description:
      "Pet supply and grooming retailer serving year-round residents and tourists.",
  },
];

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}
